// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

/*
Package opentransaction is a generated protocol buffer package.

It is generated from these files:
	transaction.proto

It has these top-level messages:
	Transaction
*/
package opentransaction

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	ID                string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	OriginTenant      string `protobuf:"bytes,2,opt,name=origin_tenant,json=originTenant" json:"origin_tenant,omitempty"`
	DestinationTenant string `protobuf:"bytes,3,opt,name=destination_tenant,json=destinationTenant" json:"destination_tenant,omitempty"`
	FromRef           string `protobuf:"bytes,4,opt,name=from_ref,json=fromRef" json:"from_ref,omitempty"`
	ToRef             string `protobuf:"bytes,5,opt,name=to_ref,json=toRef" json:"to_ref,omitempty"`
	Value             int64  `protobuf:"varint,6,opt,name=value" json:"value,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Transaction) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Transaction) GetOriginTenant() string {
	if m != nil {
		return m.OriginTenant
	}
	return ""
}

func (m *Transaction) GetDestinationTenant() string {
	if m != nil {
		return m.DestinationTenant
	}
	return ""
}

func (m *Transaction) GetFromRef() string {
	if m != nil {
		return m.FromRef
	}
	return ""
}

func (m *Transaction) GetToRef() string {
	if m != nil {
		return m.ToRef
	}
	return ""
}

func (m *Transaction) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Transaction)(nil), "opentransaction.Transaction")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TransactionService service

type TransactionServiceClient interface {
}

type transactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionServiceClient(cc *grpc.ClientConn) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

// Server API for TransactionService service

type TransactionServiceServer interface {
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opentransaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "transaction.proto",
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbf, 0x6e, 0x83, 0x30,
	0x10, 0x87, 0x65, 0x28, 0xb4, 0xbd, 0xfe, 0x13, 0x16, 0x95, 0xdc, 0x0d, 0xb5, 0x0b, 0x4b, 0x33,
	0x24, 0xaf, 0xc0, 0xc2, 0x4a, 0xd8, 0x91, 0x43, 0x8e, 0xc8, 0x52, 0xe2, 0x43, 0xe6, 0xc2, 0xbb,
	0xe5, 0xed, 0x22, 0x4c, 0xa2, 0x30, 0xfe, 0xbe, 0xef, 0x93, 0xe5, 0x83, 0x84, 0x9d, 0xb6, 0x83,
	0x6e, 0xd9, 0x90, 0x5d, 0xf5, 0x8e, 0x98, 0xe4, 0x17, 0xf5, 0x68, 0x17, 0xf8, 0xf7, 0x22, 0xe0,
	0xad, 0x7e, 0x6c, 0xf9, 0x09, 0x41, 0x59, 0x28, 0x91, 0x89, 0xfc, 0xb5, 0x0a, 0xca, 0x42, 0xfe,
	0xc1, 0x07, 0x39, 0x73, 0x30, 0xb6, 0x61, 0xb4, 0xda, 0xb2, 0x0a, 0xbc, 0x7a, 0x9f, 0x61, 0xed,
	0x99, 0xfc, 0x07, 0xb9, 0xc7, 0x81, 0x8d, 0xd5, 0xd3, 0x1b, 0xf7, 0x32, 0xf4, 0x65, 0xb2, 0x30,
	0xb7, 0xfc, 0x07, 0x5e, 0x3a, 0x47, 0xa7, 0xc6, 0x61, 0xa7, 0x9e, 0x7c, 0xf4, 0x3c, 0xed, 0x0a,
	0x3b, 0xf9, 0x0d, 0x31, 0x93, 0x17, 0x91, 0x17, 0x11, 0xd3, 0x84, 0x53, 0x88, 0x46, 0x7d, 0x3c,
	0xa3, 0x8a, 0x33, 0x91, 0x87, 0xd5, 0x3c, 0xd6, 0x29, 0xc8, 0xc5, 0xd7, 0xb7, 0xe8, 0x46, 0xd3,
	0xe2, 0x2e, 0xf6, 0x97, 0x6e, 0xae, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x51, 0xcb, 0x6d, 0xfe,
	0x00, 0x00, 0x00,
}
